var supervisor = <?=ULV>2 ? 'true' : 'false' ;?>;
var plaqueinfo_forum = 1;
var plaqueinfo_desc = "";
var plaqueinfo_logo = " ";
var plaqueinfo_status = 0;
var plaqueinfo_points = 0;
var plaqueinfo_days = 0;
var plaqueinfo_id = 0;
var plaqueinfo_needsapproval = 0;
var plaqueinfo_closed = 0;
var editCaller = "";
var moderatedForums = new Array(2,3);